# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: vote
#   name: vote
#   namespace: voting-app
# spec:
#   type: LoadBalancer
#   ports:
#   - name: "vote-service"
#     port: 80
#     protocol: TCP
#     targetPort: 80
#   selector:
#     app: vote
  
