---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: carts
spec:
  ports:
    # the port that this service should serve on
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx
  type: LoadBalancer